# Generated by Django 5.1.1 on 2024-09-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_models', '0002_alter_aircraft_operator_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='operator_airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_set', to='airport_models.airline'),
        ),
    ]
